//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class activity
{
    public int id { get; set; }
    public string idstaff { get; set; }
    public System.DateTime waktu { get; set; }
    public decimal isact { get; set; }
}

public partial class roles
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public roles()
    {
        this.staff = new HashSet<staff>();
    }

    public string rolesid { get; set; }
    public string rolenames { get; set; }
    public Nullable<decimal> parentrolesid { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<staff> staff { get; set; }
}

public partial class staff
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public staff()
    {
        this.stafflogin = new HashSet<stafflogin>();
    }

    public string staffid { get; set; }
    public string namastaff { get; set; }
    public string rolesid { get; set; }
    public string passwords { get; set; }
    public string createdby { get; set; }
    public System.DateTime createdon { get; set; }
    public string modifiedby { get; set; }
    public Nullable<System.DateTime> modifedtime { get; set; }

    public virtual roles roles { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<stafflogin> stafflogin { get; set; }
}

public partial class stafflogin
{
    public int idlogin { get; set; }
    public string staffid { get; set; }
    public System.DateTime loginstart { get; set; }
    public Nullable<System.DateTime> loginout { get; set; }
    public Nullable<decimal> islogin { get; set; }

    public virtual staff staff { get; set; }
}
